// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NAV: typeof import('naive-ui')['NAV']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NRow: typeof import('naive-ui')['NRow']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NThing: typeof import('naive-ui')['NThing']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
